baseURL = "https://balzss.github.io/receptek/"
languageCode = "hu-hu"
title = "Receptek"
theme = "recipes"
enableGitInfo = true

[params]
  author = "Balazs Saros"
  githubEditUrl= "https://github.com/balzss/static-recipes/edit/master/content/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
