baseURL = "https://receptek.bsaros.com"
languageCode = "hu-hu"
title = "Receptek"
theme = "recipes"
enableGitInfo = true

[params]
  author = "Balazs Saros"
  githubEditUrl= "https://github.com/balzss/static-recipes/edit/master/content/"
  appView = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
